# This configuration was used Ebert to review the jwt/ruby-jwt repository
# on a633b8b7fb000ac400ddb5cff18bddbfa203d637.
# You can make this the default configuration for future reviews by moving this
# file to your repository as `.ebert.yml` and pushing it to GitHub, and tweak
# it as you wish - To know more on how to change this file to better review your
# repository you can go to https://ebertapp.io/docs/config and see the configuration
# details.
---
styleguide: plataformatec/linters
engines:
  reek:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
  duplication:
    config:
      languages:
      - ruby
    enabled: true
  remark-lint:
    enabled: true
exclude_paths:
- spec

