sudo: false
language: ruby
script: "bundle exec rspec"
before_install:
  - gem update --system
  - gem --version
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - ruby-head
  - rbx-2
  - jruby-19mode
  - jruby-head
addons:
  code_climate:
    repo_token: 83c2e090282b16d91251419d1258e47c82d725056835a1daef193077cbb2a0e6
